# Generated by Django 5.1.7 on 2025-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
